version: '3.1'

services:
  rpizwsolar_server__container:
    image: rpizwsolar_server_image:latest
    build: .
    container_name: rpizwsolar_server_container
    volumes:
      - type: bind
        source: ./app
        target: /home/app
    tty: true
